version: "3.9"
services:
  postgres:
    image: postgres:14.0
    container_name: queue_postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - "./pg-init:/docker-entrypoint-initdb.d"
    networks:
      indexer:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pg-data:
    name: pg-data

networks:
  indexer:
